### ISSUE TITLE
why include babel/package build stuff in `shared-components`?

### ISSUE THREAD

**Issue by andycmaj** [fillipvt/portfolio#1]
@fillipvt question for you... why do you need to treat shared-components as an actual BUILT npm package? 

doesn't `transpileModules: ['@fillipvt/components'],` take care of doing all the "building" of that shared package when you run `next`?

**Comment by fev4** [comment]
To be honest I don't remember exactly which was the reason. But what I did encounter was a series of errors that didn't allow me to directly transpile my own module so that it was on par with all the babel config within next.js.

With trial and error decided to create my own package on npm and it worked!

Nowadays I don't use this folder structure especially with all the new improvements which have been made since next.js 8.0.2, for example:

- [The API routes](https://nextjs.org/blog/next-9#api-routes) that replaces the external graphql project
- [The recent](https://nextjs.org/blog/next-9-1) src/pages and public/static
- The 2 separate next.js apps, in the end, even with the help of yarn workspaces, caused the whole process of adding and removing dependencies to be more troublesome than I should've been.
- And a lot more done in Now 2.0

So, I'll be moving this portfolio project to the newest version when I get the chance. This stack is moving rapidly!

I'm sorry I didn't get to answer your question directly, but I don't remember the specific error that prompted me to move to the npm solution. But I hope everything else in the response helps a bit.

**Comment by andycmaj** [comment]
great! it's very useful to have the background context there... and yeah Now2/next9 basically caused every example to be obsolete :)

thanks again for taking the time to answer.
